### ISSUE TITLE
Exporter warning

### ISSUE THREAD

**Issue by ksobon** [kmorin/nwcautoviewexporter#2]
Hi Kyle,

Quick question. Is there a way to handle/suppress this warning when exporting to NWC? 

![image](https://cloud.githubusercontent.com/assets/529781/13162896/4baf6520-d676-11e5-9025-c8356505c1e7.png)

Any help is much appreciated. 

Cheers!

**Comment by kmorin** [comment]
@ksobon That is a built-in dialog, the only way would be to prevent that would be to intercept the failure definition id and supress.
